#nullable enable

using System.Text;

namespace AIGuiders.Platform.Execution.Documentation.Reports;

public static class MarkdownNotationVocabularyWriter
{
    public static string Write(NotationVocabularyFactSet facts, DateTimeOffset generatedAtUtc)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- Generated by NotationGlossaryReport — do not edit by hand. -->");
        sb.AppendLine($"<!-- Generated at: {generatedAtUtc:O} -->");
        sb.AppendLine();
        sb.AppendLine("# Notation vocabulary (generated)");
        sb.AppendLine();
        sb.AppendLine("Federation argument reader ids and catalog field aliases. Regenerate:");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("dotnet run --project tools/NotationGlossaryReport -- --write docs/NOTATION-VOCABULARY.generated.md");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine($"_Updated: {generatedAtUtc:yyyy-MM-dd HH:mm} UTC_");
        sb.AppendLine();
        sb.AppendLine("## Argument ReaderId");
        sb.AppendLine();
        sb.AppendLine("Catalog TOML/JSON uses **`tail_wire_class`** / **`tailWireClass`**; normalized argument wire uses **`ReaderId`** on `NormalizedArguments` / `ArgumentNotationProfile`.");
        sb.AppendLine();
        sb.AppendLine("| ReaderId | Constant | Catalog field | Catalog value |");
        sb.AppendLine("|----------|----------|---------------|---------------|");

        foreach (var row in facts.ArgumentReaders)
        {
            sb.AppendLine(
                $"| `{row.ReaderId}` | `{row.ConstantName}` | `{row.CatalogField}` | `{row.CatalogValue}` |");
        }

        sb.AppendLine();
        sb.AppendLine("## Notations packages (scan)");
        sb.AppendLine();
        sb.AppendLine("| PackageId | Hyperlane hint |");
        sb.AppendLine("|-----------|----------------|");

        foreach (var row in facts.NotationPackages)
            sb.AppendLine($"| `{row.PackageId}` | {row.HyperlaneHint} |");

        if (facts.NotationPackages.Count == 0)
            sb.AppendLine("| _no packages scanned_ | — |");

        sb.AppendLine();
        sb.AppendLine("Inline ADR symbol refs: `[Family:doc; Type:…; Member:…]` — see [GUIDERS-ADR-0027](adr/GUIDERS-ADR-0027-mdlinker-doc-anchor-check.md).");
        return sb.ToString();
    }
}
