using System.Text;
using AIGuiders.Platform.Authoring.Command.Catalog;

namespace AIGuiders.Platform.CommandPlane.Catalog.CodeGen;

/// <summary>Emit a planet catalog partial class from parsed <c>.catalog</c> IR (GUIDERS-ADR-0047).</summary>
public static class CatalogCatalogEmitter
{
    public static string EmitCSharp(
        CatalogDocument document,
        string namespaceName,
        string className = "Catalog")
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string Planet = \"{Escape(document.Planet)}\";");
        sb.AppendLine();
        sb.AppendLine("    public static readonly string[] FederationSurfaces =");
        sb.AppendLine("    [");
        foreach (var surface in document.FederationSurfaces())
        {
            sb.AppendLine($"        \"{Escape(surface)}\",");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, string> WireCommandIds =");
        sb.AppendLine("        new Dictionary<string, string>(StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var command in document.Commands)
        {
            var wire = document.WireCommandId(command.Command);
            sb.AppendLine($"        [\"{Escape(command.Command)}\"] = \"{Escape(wire)}\",");
        }

        sb.AppendLine("    };");

        if (document.Executors.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    public static readonly IReadOnlyDictionary<string, string> Executors =");
            sb.AppendLine("        new Dictionary<string, string>(StringComparer.Ordinal)");
            sb.AppendLine("    {");
            foreach (var (command, executor) in document.Executors)
            {
                sb.AppendLine($"        [\"{Escape(command)}\"] = \"{Escape(executor)}\",");
            }

            sb.AppendLine("    };");
        }

        if (document.Mcp.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    public static readonly string[] ExposedMcpCommands =");
            sb.AppendLine("    [");
            foreach (var row in document.Mcp.Where(static r => r.Expose.Equals("yes", StringComparison.OrdinalIgnoreCase)))
            {
                sb.AppendLine($"        \"{Escape(document.WireCommandId(row.Command))}\",");
            }

            sb.AppendLine("    ];");
        }

        EmitPhraseSlots(sb, document);

        sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitPhraseSlots(StringBuilder sb, CatalogDocument document)
    {
        var index = CatalogPhraseSlotIndex.FromDocument(document);
        if (index.Commands.Count == 0)
        {
            return;
        }

        var labels = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var command in index.Commands)
        {
            foreach (var (slot, label) in command.SlotLabels)
            {
                labels[slot] = label;
            }
        }

        sb.AppendLine();
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, string> PhraseSlotLabels =");
        sb.AppendLine("        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");
        foreach (var (slot, label) in labels.OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine($"        [\"{Escape(slot)}\"] = \"{Escape(label)}\",");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static readonly CatalogPhraseSlotEmit[] PhraseSlotCommands =");
        sb.AppendLine("    [");
        foreach (var command in index.Commands)
        {
            var fills = string.Join(", ", command.Fills.Select(fill => $"\"{Escape(fill)}\""));
            sb.AppendLine(
                $"        new(\"{Escape(command.CatalogCommand)}\", \"{Escape(command.WireCommandId)}\", \"{Escape(command.LiteralPrefix)}\", [{fills}]),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    public static CatalogPhraseSlotIndex PhraseSlots =>");
        sb.AppendLine("        CatalogPhraseSlotIndex.FromEmitted(PhraseSlotCommands, PhraseSlotLabels);");
    }

    static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
