using System.Text;
using AIGuiders.Platform.Authoring.Command.Catalog;

namespace AIGuiders.Platform.Execution.CommandPlane.Catalog.CodeGen;

/// <summary>Emit a planet catalog partial class from parsed <c>.catalog</c> IR (GUIDERS-ADR-0047).</summary>
public static class CatalogCatalogEmitter
{
    public static string EmitCSharp(
        CatalogDocument document,
        string namespaceName,
        string className = "Catalog")
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using AIGuiders.Platform.Authoring.Command.Catalog;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string Planet = \"{Escape(document.Planet)}\";");
        sb.AppendLine();
        sb.AppendLine("    public static readonly string[] FederationSurfaces =");
        sb.AppendLine("    [");
        foreach (var surface in document.FederationSurfaces())
        {
            sb.AppendLine($"        \"{Escape(surface)}\",");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, string> WireCommandIds =");
        sb.AppendLine("        new Dictionary<string, string>(StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var command in document.Commands)
        {
            var wire = document.WireCommandId(command.Command);
            sb.AppendLine($"        [\"{Escape(command.Command)}\"] = \"{Escape(wire)}\",");
        }

        sb.AppendLine("    };");

        if (document.Executors.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    public static readonly IReadOnlyDictionary<string, string> Executors =");
            sb.AppendLine("        new Dictionary<string, string>(StringComparer.Ordinal)");
            sb.AppendLine("    {");
            foreach (var (command, executor) in document.Executors)
            {
                sb.AppendLine($"        [\"{Escape(command)}\"] = \"{Escape(executor)}\",");
            }

            sb.AppendLine("    };");
        }

        if (document.Mcp.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    public static readonly string[] ExposedMcpCommands =");
            sb.AppendLine("    [");
            foreach (var row in document.Mcp.Where(static r => r.Expose.Equals("yes", StringComparison.OrdinalIgnoreCase)))
            {
                sb.AppendLine($"        \"{Escape(document.WireCommandId(row.Command))}\",");
            }

            sb.AppendLine("    ];");
        }

        EmitPhraseSlots(sb, document);
        EmitDocument(sb, document);

        sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitDocument(StringBuilder sb, CatalogDocument document)
    {
        sb.AppendLine();
        sb.AppendLine("    public static CatalogDocument Document { get; } = CreateDocument();");
        sb.AppendLine();
        sb.AppendLine("    static CatalogDocument CreateDocument() => new()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Planet = \"{Escape(document.Planet)}\",");
        EmitStringList(sb, "Imports", document.Imports, 2);
        EmitDefaults(sb, document.Defaults);
        EmitChannels(sb, document.Channels);
        EmitNameList(sb, "Variables", document.Variables, static v => v.Name, static v => v.Kind);
        EmitHelps(sb, document.Helps);
        EmitPhrases(sb, document.Phrases);
        EmitProfiles(sb, document.Profiles);
        EmitCommands(sb, document.Commands);
        EmitBindings(sb, document.Bindings);
        EmitMelodies(sb, document.Melodies);
        EmitMcpRows(sb, document.Mcp);
        if (document.Executors.Count > 0)
        {
            EmitStringDictionary(sb, "Executors", document.Executors, 2);
        }

        sb.AppendLine("    };");
    }

    static void EmitDefaults(StringBuilder sb, CatalogDefaults defaults)
    {
        sb.AppendLine("        Defaults = new CatalogDefaults");
        sb.AppendLine("        {");
        EmitOptionalStringProperty(sb, "VariableKind", defaults.VariableKind, 3);
        EmitOptionalStringProperty(sb, "CommandScope", defaults.CommandScope, 3);
        EmitStringList(sb, "CommandSurfaces", defaults.CommandSurfaces, 3);
        EmitOptionalStringProperty(sb, "GrammarKeyboardBinding", defaults.GrammarKeyboardBinding, 3);
        EmitOptionalStringProperty(sb, "GrammarKeyboardMelody", defaults.GrammarKeyboardMelody, 3);
        EmitOptionalStringProperty(sb, "BindingChordRoot", defaults.BindingChordRoot, 3);
        EmitOptionalStringProperty(sb, "CommandFlavor", defaults.CommandFlavor, 3);
        sb.AppendLine("        },");
    }

    static void EmitChannels(StringBuilder sb, IReadOnlyList<CatalogChannel> channels)
    {
        if (channels.Count == 0)
        {
            return;
        }

        sb.AppendLine("        Channels =");
        sb.AppendLine("        [");
        foreach (var channel in channels)
        {
            sb.AppendLine("            new CatalogChannel");
            sb.AppendLine("            {");
            sb.AppendLine($"                Surface = \"{Escape(channel.Surface)}\",");
            EmitOptionalStringProperty(sb, "Sub", channel.Sub, 4);
            EmitOptionalStringProperty(sb, "PlanetId", channel.PlanetId, 4);
            EmitOptionalStringProperty(sb, "CommandGrammar", channel.CommandGrammar, 4);
            EmitOptionalStringProperty(sb, "ArgumentGrammar", channel.ArgumentGrammar, 4);
            sb.AppendLine("            },");
        }

        sb.AppendLine("        ],");
    }

    static void EmitNameList<T>(
        StringBuilder sb,
        string propertyName,
        IReadOnlyList<T> items,
        Func<T, string> name,
        Func<T, string?> kind)
    {
        if (items.Count == 0)
        {
            return;
        }

        sb.AppendLine($"        {propertyName} =");
        sb.AppendLine("        [");
        foreach (var item in items)
        {
            var kindValue = kind(item);
            if (string.IsNullOrWhiteSpace(kindValue))
            {
                sb.AppendLine($"            new CatalogVariable(\"{Escape(name(item))}\", null),");
            }
            else
            {
                sb.AppendLine($"            new CatalogVariable(\"{Escape(name(item))}\", \"{Escape(kindValue)}\"),");
            }
        }

        sb.AppendLine("        ],");
    }

    static void EmitHelps(StringBuilder sb, IReadOnlyList<CatalogHelp> helps)
    {
        if (helps.Count == 0)
        {
            return;
        }

        sb.AppendLine("        Helps =");
        sb.AppendLine("        [");
        foreach (var help in helps)
        {
            sb.AppendLine(
                $"            new CatalogHelp(\"{Escape(help.Target)}\", \"{Escape(help.Field)}\", \"{Escape(help.Text)}\"),");
        }

        sb.AppendLine("        ],");
    }

    static void EmitPhrases(StringBuilder sb, IReadOnlyList<CatalogPhrase> phrases)
    {
        if (phrases.Count == 0)
        {
            return;
        }

        sb.AppendLine("        Phrases =");
        sb.AppendLine("        [");
        foreach (var phrase in phrases)
        {
            sb.AppendLine(
                $"            new CatalogPhrase(\"{Escape(phrase.Name)}\", \"{Escape(phrase.Phrase)}\"),");
        }

        sb.AppendLine("        ],");
    }

    static void EmitProfiles(StringBuilder sb, IReadOnlyList<CatalogProfile> profiles)
    {
        if (profiles.Count == 0)
        {
            return;
        }

        sb.AppendLine("        Profiles =");
        sb.AppendLine("        [");
        foreach (var profile in profiles)
        {
            sb.AppendLine("            new CatalogProfile");
            sb.AppendLine("            {");
            sb.AppendLine($"                Name = \"{Escape(profile.Name)}\",");
            EmitOptionalStringProperty(sb, "BundleSource", profile.BundleSource, 4);
            if (profile.Entries.Count > 0)
            {
                sb.AppendLine("                Entries =");
                sb.AppendLine("                [");
                foreach (var entry in profile.Entries)
                {
                    sb.AppendLine(
                        $"                    new CatalogProfileEntry(\"{Escape(entry.Arg)}\", \"{Escape(entry.Entry)}\", \"{Escape(entry.Ref)}\"),");
                }

                sb.AppendLine("                ],");
            }

            sb.AppendLine("            },");
        }

        sb.AppendLine("        ],");
    }

    static void EmitCommands(StringBuilder sb, IReadOnlyList<CatalogCommandRow> commands)
    {
        if (commands.Count == 0)
        {
            return;
        }

        sb.AppendLine("        Commands =");
        sb.AppendLine("        [");
        foreach (var command in commands)
        {
            sb.AppendLine("            new CatalogCommandRow");
            sb.AppendLine("            {");
            sb.AppendLine($"                Command = \"{Escape(command.Command)}\",");
            sb.AppendLine("                Columns = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("                {");
            foreach (var (key, value) in command.Columns.OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
            {
                sb.AppendLine($"                    [\"{Escape(key)}\"] = \"{Escape(value)}\",");
            }

            sb.AppendLine("                },");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        ],");
    }

    static void EmitBindings(StringBuilder sb, IReadOnlyList<CatalogBindingRow> bindings)
    {
        if (bindings.Count == 0)
        {
            return;
        }

        sb.AppendLine("        Bindings =");
        sb.AppendLine("        [");
        foreach (var binding in bindings)
        {
            sb.AppendLine(
                $"            new CatalogBindingRow(\"{Escape(binding.Gesture)}\", \"{Escape(binding.Command)}\", {OptionalString(binding.Role)}),");
        }

        sb.AppendLine("        ],");
    }

    static void EmitMelodies(StringBuilder sb, IReadOnlyList<CatalogMelodyRow> melodies)
    {
        if (melodies.Count == 0)
        {
            return;
        }

        sb.AppendLine("        Melodies =");
        sb.AppendLine("        [");
        foreach (var melody in melodies)
        {
            sb.AppendLine(
                $"            new CatalogMelodyRow(\"{Escape(melody.Slug)}\", \"{Escape(melody.Command)}\"),");
        }

        sb.AppendLine("        ],");
    }

    static void EmitMcpRows(StringBuilder sb, IReadOnlyList<CatalogMcpRow> rows)
    {
        if (rows.Count == 0)
        {
            return;
        }

        sb.AppendLine("        Mcp =");
        sb.AppendLine("        [");
        foreach (var row in rows)
        {
            sb.AppendLine(
                $"            new CatalogMcpRow(\"{Escape(row.Command)}\", \"{Escape(row.Expose)}\"),");
        }

        sb.AppendLine("        ],");
    }

    static void EmitStringList(
        StringBuilder sb,
        string propertyName,
        IReadOnlyList<string> values,
        int indent,
        string? ownerPrefix = null)
    {
        var pad = new string(' ', indent * 4);
        var fullName = ownerPrefix is null ? propertyName : $"{ownerPrefix}.{propertyName}";
        if (values.Count == 0)
        {
            sb.AppendLine($"{pad}{fullName} = [],");
            return;
        }

        sb.AppendLine($"{pad}{fullName} =");
        sb.AppendLine($"{pad}[");
        foreach (var value in values)
        {
            sb.AppendLine($"{pad}    \"{Escape(value)}\",");
        }

        sb.AppendLine($"{pad}],");
    }

    static void EmitStringDictionary(
        StringBuilder sb,
        string propertyName,
        IReadOnlyDictionary<string, string> values,
        int indent)
    {
        var pad = new string(' ', indent * 4);
        sb.AppendLine($"{pad}{propertyName} = new Dictionary<string, string>(StringComparer.Ordinal)");
        sb.AppendLine($"{pad}{{");
        foreach (var (key, value) in values.OrderBy(static pair => pair.Key, StringComparer.Ordinal))
        {
            sb.AppendLine($"{pad}    [\"{Escape(key)}\"] = \"{Escape(value)}\",");
        }

        sb.AppendLine($"{pad}}},");
    }

    static void EmitOptionalStringProperty(StringBuilder sb, string name, string? value, int indent)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return;
        }

        var pad = new string(' ', indent * 4);
        sb.AppendLine($"{pad}{name} = \"{Escape(value)}\",");
    }

    static string OptionalString(string? value) =>
        string.IsNullOrWhiteSpace(value) ? "null" : $"\"{Escape(value)}\"";

    static void EmitPhraseSlots(StringBuilder sb, CatalogDocument document)
    {
        var index = CatalogPhraseSlotIndex.FromDocument(document);
        if (index.Commands.Count == 0)
        {
            return;
        }

        var labels = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var command in index.Commands)
        {
            foreach (var (slot, label) in command.SlotLabels)
            {
                labels[slot] = label;
            }
        }

        sb.AppendLine();
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, string> PhraseSlotLabels =");
        sb.AppendLine("        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");
        foreach (var (slot, label) in labels.OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine($"        [\"{Escape(slot)}\"] = \"{Escape(label)}\",");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static readonly CatalogPhraseSlotEmit[] PhraseSlotCommands =");
        sb.AppendLine("    [");
        foreach (var command in index.Commands)
        {
            var fills = string.Join(", ", command.Fills.Select(fill => $"\"{Escape(fill)}\""));
            sb.AppendLine(
                $"        new(\"{Escape(command.CatalogCommand)}\", \"{Escape(command.WireCommandId)}\", \"{Escape(command.LiteralPrefix)}\", [{fills}]),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    public static CatalogPhraseSlotIndex PhraseSlots =>");
        sb.AppendLine("        CatalogPhraseSlotIndex.FromEmitted(PhraseSlotCommands, PhraseSlotLabels);");
    }

    static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
