global using AIGuiders.Platform.Execution.CommandPlane.ArgSuggestions;
global using AIGuiders.Platform.IntermediateRepresentation.Command;
global using CommandArgTailKind = AIGuiders.Platform.Modeling.Gdl.Command.CommandArgTailKind;
global using CommandPickerChoiceKind = AIGuiders.Platform.Modeling.Gdl.Command.CommandPickerChoiceKind;
global using CatalogPathRole = AIGuiders.Platform.Modeling.Gdl.Command.CatalogPathRole;
global using CommandDocumentFormat = AIGuiders.Platform.Modeling.Gdl.Command.CommandDocumentFormat;
global using CommandPickerChoice = AIGuiders.Platform.Modeling.Gdl.Command.CommandPickerChoice;
global using ArgConstructorBinding = AIGuiders.Platform.Modeling.Gdl.Command.ArgConstructorBinding;
global using CatalogRouteEntry = AIGuiders.Platform.Modeling.Gdl.Command.CatalogRouteEntry;
global using CatalogSemanticFields = AIGuiders.Platform.Modeling.Gdl.Command.CatalogSemanticFields;
global using ArgTailEntryKind = AIGuiders.Platform.Modeling.Gdl.Command.ArgTailEntryKind;
global using ArgTailMenuEntry = AIGuiders.Platform.Modeling.Gdl.Command.ArgTailMenuEntry;
global using ArgTailProfile = AIGuiders.Platform.Modeling.Gdl.Command.ArgTailProfile;
