using System.Text;

namespace AIGuiders.Platform.Utilities.Adoption;

public static class AllianceReportWriter
{
    public static string ToMarkdown(
        IReadOnlyList<PlanetAdoptionRow> rows,
        DateTimeOffset generatedAtUtc)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- Generated by AdoptionReport — do not edit by hand. -->");
        sb.AppendLine($"<!-- Generated at: {generatedAtUtc:O} -->");
        sb.AppendLine();
        sb.AppendLine("# Adoption alliance (generated)");
        sb.AppendLine();
        sb.AppendLine("Machine-readable pact view: which planets pin which hyperlanes. Regenerate:");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("dotnet run --project tools/AdoptionReport -- --write docs/ADOPTION-ALLIANCE.generated.md");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine($"_Updated: {generatedAtUtc:yyyy-MM-dd HH:mm} UTC_");
        sb.AppendLine();
        sb.AppendLine("| Planet | Hyperlane | Port | Packages | Spec tags | Issues |");
        sb.AppendLine("|--------|-----------|------|----------|-----------|--------|");

        foreach (var row in rows.OrderBy(r => r.PlanetId, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(r => r.Hyperlane, StringComparer.OrdinalIgnoreCase))
        {
            var issues = string.IsNullOrWhiteSpace(row.IssuesUrl)
                ? "—"
                : $"[{row.PlanetId}]({row.IssuesUrl})";
            sb.AppendLine(
                $"| **{row.PlanetName}** (`{row.PlanetId}`) | {row.Hyperlane} | {row.Port} | {EscapeCell(row.Packages)} | {EscapeCell(row.SpecTags)} | {issues} |");
        }

        if (rows.Count == 0)
            sb.AppendLine("| _no planets scanned_ | — | — | — | — | — |");

        sb.AppendLine();
        sb.AppendLine("See [Constitution § Adoption alliances](GUIDERS-FEDERATION-CONSTITUTION.md#adoption-alliances-real-not-decorative).");
        return sb.ToString();
    }

    private static string EscapeCell(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "—";
        return value.Replace("|", "/");
    }
}
